amcl: 
  ros__parameters:
    use_sim_time: false

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 20.0

    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001

    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller/RegulatedPurePursuitController"

      desired_linear_vel: 0.25
      max_linear_accel: 1.5
      max_linear_decel: 1.5
      max_angular_vel: 1.0

      lookahead_dist: 0.6
      min_lookahead_dist: 0.3
      max_lookahead_dist: 0.9
      lookahead_time: 1.5

      rotate_to_heading_angular_vel: 1.8
      transform_tolerance: 0.1

      use_velocity_scaled_lookahead_dist: true
      use_approach_linear_velocity_scaling: true
      approach_velocity_scaling_dist: 0.6

      use_collision_detection: true
      max_allowed_time_to_collision_up_to_carrot: 1.3
      use_cost_regulated_linear_velocity_scaling: true
      cost_scaling_dist: 0.6
      cost_scaling_gain: 1.0

      allow_reversing: false
      use_rotate_to_heading: true
      rotate_to_heading_min_angle: 0.785
      rotate_to_heading_lookahead_dist: 0.6


# controller_server:
#   ros__parameters:
#     use_sim_time: false
#     controller_frequency: 20.0

#     min_x_velocity_threshold: 0.001
#     min_y_velocity_threshold: 0.001
#     min_theta_velocity_threshold: 0.001

#     # main local planner
#     controller_plugins: ["FollowPath"]

#     FollowPath:
#       plugin: "dwb_core::DWBLocalPlanner"
#       debug_trajectory_details: false

#       # critics: [
#         # "ConstraintCritic", "CostCritic", "GoalCritic",
#         # "GoalAngleCritic", "PathAlignCritic", "PathFollowCritic",
#         # "PathAngleCritic", "PreferForwardCritic"
#       # ]
#       critics: ["RotateToGoal", "ObstacleFootprint", "GoalAlign", "PathAlign", "PathDist"]

#       PathAlign:
#         plugin: "dwb_critics::PathAlignCritic"
#       GoalAlign:
#         plugin: "dwb_critics::GoalAlignCritic"
#       PathDist:
#         plugin: "dwb_critics::PathDistCritic"
#       GoalDist:
#         plugin: "dwb_critics::GoalDistCritic"
#       ObstacleFootprint:
#         plugin: "dwb_critics::ObstacleFootprintCritic"
#       RotateToGoal:
#         plugin: "dwb_critics::RotateToGoalCritic"

planner_server:
  ros__parameters:
    use_sim_time: false
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5

bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: "map"           # will be remapped per robot
    robot_base_frame: "base_link" # will be remapped per robot
    default_nav_to_pose_bt_xml: "navigate_w_replanning_and_recovery.xml"

behavior_server:
  ros__parameters:
    use_sim_time: false

smoother_server:
  ros__parameters:
    use_sim_time: false

waypoint_follower:
  ros__parameters:
    use_sim_time: false

# Costmaps
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: "map"           # remap per robot
      robot_base_frame: "base_link" # remap per robot
      use_footprint: true
      update_frequency: 5.0
      publish_frequency: 1.0
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_topic: "map"            # remap per robot
        subscribe_to_updates: true
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: "scan"
        scan:
          topic: "scan"
          max_obstacle_height: 2.0
          clearing: true
          marking: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.4

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: "odom"          # remap per robot
      robot_base_frame: "base_link" # remap per robot
      update_frequency: 20.0
      publish_frequency: 5.0
      rolling_window: true
      width: 4.0
      height: 4.0
      resolution: 0.05
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_topic: "map"            # remap per robot
        subscribe_to_updates: true
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: "scan"
        scan:
          topic: "scan"
          max_obstacle_height: 2.0
          clearing: true
          marking: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.4
