slam_toolbox_robot2:
  ros__parameters:
    use_sim_time: false

    odom_frame: "odom_robot2"
    map_frame: "robot2/map"
    base_frame: "robot2/base_link"

    scan_topic: "scan"

    publish_to_tf: true
    resolution: 0.05
    publish_period: 0.5
    max_laser_range: 20.0
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.1745
